version: "3"
services:
  challenge:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
